import { NextPage } from "next";
import Head from "next/head";
import StickyFooter from "@/components/layouts/StickyFooter";
import YouTube from "@/components/views/Media";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>God Ussop</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <YouTube />
      <StickyFooter />
    </>
  );
};

export default Index;
